title: Kazuto Nishimori # your name (or website title) here
logo: "/images/ProfilePic.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello! I am a 2021 graduate from Middlebury College with a degree in Physics, Geography, and French. I am interested in cartography, design, spatial analysis and data visualization.
  <br><br>
  I was born in Tokyo and split my time between there and Brookline, MA until high school. Then, I moved to the beautiful Middlebury College nested between the Adirondacks and Green Mountains. Some of my hobbies include homebrewing, carpentry, and darkroom photography.
  <br><br>
  <a href="https://www.linkedin.com/in/kazutonishimori/>View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: G-2P0SS7W746 # your Google Analytics tracking ID here
